#pragma once
#define Pthread_mutex_init pthread_mutex_init
#define Pthread_mutex_lock pthread_mutex_lock
#define Pthread_mutex_unlock pthread_mutex_unlock
#define Pthread_cond_signal pthread_cond_signal
#define Pthread_cond_wait pthread_cond_wait
#define Pthread_create pthread_create
#define Pthread_join pthread_join
#define Pthread_cond_init pthread_cond_init
